### ISSUE TITLE
`v2.1.0` introduces a breaking change from `v2.0.x`

### ISSUE THREAD

**Issue by tonybaroneee** [Siilwyn/prettier-plugin-css-order#41]
Hello! Just wanted to bring awareness to a breaking change in `v2.1.0`.

We have this plugin in our package.json as follows:

`"prettier-plugin-css-order": "^2.0.1",`

We use `cssDeclarationSorterOrder: 'alphabetical'` in our `.prettierrc.yaml`. With the new release, our GitHub workflow must be pulling in 2.1.0 instead, and since `cssDeclarationSorterCustomOrder` is not declared, our GitHub formatter workflow now fails suddenly.

Perhaps the plugin should gracefully handle not supplying the new `cssDeclarationSorterCustomOrder` option? Minor updates should ideally not include breaking changes, that should be in a major version bump according to [semver](https://semver.org/).

I'm sure this probably broke other workflows besides ours :) Thanks!

**Comment by Siilwyn** [comment]
What exactly breaks? Does Prettier complain about the missing option? Because the code does check if the option is given

**Comment by claudiopro** [comment]
I was hit by the same issue after an upgrade to `v2.1.0`. The plugin now requires the `"cssDeclarationSorterCustomOrder"` config option, and if set, it always overrides the `"cssDeclarationSorterOrder"` option. I'm not familiar with Prettier plugins, but `"cssDeclarationSorterCustomOrder"` should be made optional.

In order to reproduce, it is sufficient to use a Prettier config missing the `"cssDeclarationSorterCustomOrder"` option:


### Error
```
$ prettier **/*.css --write
styles/default.css
[error] Invalid cssDeclarationSorterCustomOrder value. Expected an array of a string, but received undefined.
```

### .prettierrc
```json
{
  "cssDeclarationSorterOrder": "alphabetical",
  "plugins": ["prettier-plugin-css-order"]
}
```

**Comment by tonybaroneee** [comment]
Yup, exactly what @claudiopro said.

**Comment by Siilwyn** [comment]
Thanks for the reproduction @claudiopro! Seems like the CLI does a different validation from using the Prettier JS API which is used in the tests.

Don't have time to fix this now so I reverted the change, I think the way to fix this is using a default value like @SavaCool122 had in his PR. I don't understand why the need for the `value` object though.

**Comment by claudiopro** [comment]
Super! I tried to set a default and check for an empty array (see https://github.com/claudiopro/prettier-plugin-css-order/commit/bec1e81aaeca4ac4a9f805fb613d7e561e1746e8) but I'm now hitting another issue: 

```
$ prettier --write styles/*.css
[error] Cannot read properties of undefined (reading 'value')
error Command failed with exit code 1.
```

This is currently above my head to be helpful 😅 Thanks for the quick response!

**Comment by SavaCool122** [comment]
> Don't have time to fix this now so I reverted the change, I think the way to fix this is using a default value like @SavaCool122


@Siilwyn since I was the one who made the new edits I'd be happy to help with this one. I did a little research and made a couple of demos.

**Demo with the error in v2.1.0:** https://stackblitz.com/edit/node-8vu5dp?file=package.json

**Explanation:**
Prettier check choice option [here](https://github.com/prettier/prettier/blob/d970deed6b6cabe21fdb35249265d766932b5718/src/main/normalize-options.js#L130-L142) by [ikatyang/vnopts](https://github.com/) and as I can see [here](https://github.com/ikatyang/vnopts?tab=readme-ov-file#default) it use `{value: any} `as default representation of the value throughout the code. That's why it require to use default value for array like this

```js
{
...
default: [{value: []}]
...
}
```

What is interesting is that Prettier make transforms and in `options.cssDeclarationSorterCustomOrder` comes an array. This can be seen in the working demo below

**Demo with bug fix:** https://stackblitz.com/edit/node-wn5mqt?file=package.json

I copied code of v2.1.0 and add default value as required by prettier schema validator

**Test improvement:**

At the moment I don't know how to do it. This is an interesting question for me. I would be happy to find a way to test something like this in tests

**Comment by Siilwyn** [comment]
@SavaCool122 :muscle: thanks a ton for investigating!
Prettier docs regarding options are pretty much non-existent so this really helps.

Made a PR: https://github.com/Siilwyn/prettier-plugin-css-order/pull/42
Could you take a final look so I can add back the new feature

**Comment by Siilwyn** [comment]
Re-introduced the feature in a new patch version.
