### ISSUE TITLE
[error] require() of ES Module 

### ISSUE THREAD

**Issue by lgradzki-cksource** [Siilwyn/prettier-plugin-css-order#43]
Hi there,

Awesome plugin, guys. It's working great with 'run on save' in WebStorm.
However, when trying to execute it using the CLI, I encountered the following errors.
```
prettier --write some-file
```

```
[error] require() of ES Module /Users/user/work/project/node_modules/prettier-plugin-css-order/src/main.mjs not supported.
[error] Instead change the require of /Users/user/work/project/node_modules/prettier-plugin-css-order/src/main.mjs to a dynamic import() which is available in all CommonJS modules.
```

I tried it on both Node.js 16.x.x and 18.x.x.

**Comment by notngan** [comment]
Hey I ran into this issue as well. It's caused by incompatible Prettier version. The latest version of the plugin requires Prettier [v3](https://github.com/Siilwyn/prettier-plugin-css-order/blob/main/package.json#L23) so if you're using a lower version you might want to upgrade Prettier to v3. Alternatively, you could downgrade the plugin to v1 which is compatible with Prettier v2.
